version: 0.2

phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      - echo "install phase is done"
  pre_build:
    commands:
      - GIT_SHORT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - CI=true
      - npm install
      - npm run test
      - echo "pre_build phase is done"
  build:
    commands:
      - npm run build
      - echo "build phase is done"
  post_build:
    commands:
      - echo "post_build phase is done"

artifacts:
  files:
    - build/*
  name: oak-$GIT_SHORT
